# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Requirement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Requirement.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\013Beihang.NLP',
  serialized_pb=b'\n\x11Requirement.proto\"-\n\x0cReSplitValue\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x01(\t\"8\n\x07ReValue\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x01(\t\x12\x0e\n\x06value2\x18\x03 \x01(\t\")\n\x08synValue\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x01(\t\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t2\x90\x02\n\x0bRequirement\x12*\n\x08Itemized\x12\r.ReSplitValue\x1a\r.ReSplitValue\"\x00\x12&\n\x0eRelate_Re_Sugg\x12\x08.ReValue\x1a\x08.ReValue\"\x00\x12\"\n\x08GetChSyn\x12\t.synValue\x1a\t.synValue\"\x00\x12#\n\x0fstructurization\x12\x06.Value\x1a\x06.Value\"\x00\x12\"\n\x0e\x63onflictdetect\x12\x06.Value\x1a\x06.Value\"\x00\x12 \n\x0crelationship\x12\x06.Value\x1a\x06.Value\"\x00\x12\x1e\n\nsimilarity\x12\x06.Value\x1a\x06.Value\"\x00\x42\r\n\x0b\x42\x65ihang.NLPb\x06proto3'
)




_RESPLITVALUE = _descriptor.Descriptor(
  name='ReSplitValue',
  full_name='ReSplitValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ReSplitValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='ReSplitValue.value1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=66,
)


_REVALUE = _descriptor.Descriptor(
  name='ReValue',
  full_name='ReValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ReValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='ReValue.value1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='ReValue.value2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=124,
)


_SYNVALUE = _descriptor.Descriptor(
  name='synValue',
  full_name='synValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='synValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value1', full_name='synValue.value1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=167,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Value.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['ReSplitValue'] = _RESPLITVALUE
DESCRIPTOR.message_types_by_name['ReValue'] = _REVALUE
DESCRIPTOR.message_types_by_name['synValue'] = _SYNVALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReSplitValue = _reflection.GeneratedProtocolMessageType('ReSplitValue', (_message.Message,), {
  'DESCRIPTOR' : _RESPLITVALUE,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:ReSplitValue)
  })
_sym_db.RegisterMessage(ReSplitValue)

ReValue = _reflection.GeneratedProtocolMessageType('ReValue', (_message.Message,), {
  'DESCRIPTOR' : _REVALUE,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:ReValue)
  })
_sym_db.RegisterMessage(ReValue)

synValue = _reflection.GeneratedProtocolMessageType('synValue', (_message.Message,), {
  'DESCRIPTOR' : _SYNVALUE,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:synValue)
  })
_sym_db.RegisterMessage(synValue)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'Requirement_pb2'
  # @@protoc_insertion_point(class_scope:Value)
  })
_sym_db.RegisterMessage(Value)


DESCRIPTOR._options = None

_REQUIREMENT = _descriptor.ServiceDescriptor(
  name='Requirement',
  full_name='Requirement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=194,
  serialized_end=466,
  methods=[
  _descriptor.MethodDescriptor(
    name='Itemized',
    full_name='Requirement.Itemized',
    index=0,
    containing_service=None,
    input_type=_RESPLITVALUE,
    output_type=_RESPLITVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Relate_Re_Sugg',
    full_name='Requirement.Relate_Re_Sugg',
    index=1,
    containing_service=None,
    input_type=_REVALUE,
    output_type=_REVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetChSyn',
    full_name='Requirement.GetChSyn',
    index=2,
    containing_service=None,
    input_type=_SYNVALUE,
    output_type=_SYNVALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='structurization',
    full_name='Requirement.structurization',
    index=3,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='conflictdetect',
    full_name='Requirement.conflictdetect',
    index=4,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='relationship',
    full_name='Requirement.relationship',
    index=5,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='similarity',
    full_name='Requirement.similarity',
    index=6,
    containing_service=None,
    input_type=_VALUE,
    output_type=_VALUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUIREMENT)

DESCRIPTOR.services_by_name['Requirement'] = _REQUIREMENT

# @@protoc_insertion_point(module_scope)
